name: node_js
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    build:
     runs-on: ubuntu-latest
     strategy:
      matrix:
        PACKAGE_LOCATION: [client, server]
     steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: lts/*

      - name: Build
        run: |
          cd $PACKAGE_LOCATION
          npm ci
          npm run format
          npm run lint
          npm run build
          npm run test
 
